# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_quotes', to='exam2app.User')),
                ('user', models.ManyToManyField(related_name='quotes', to='exam2app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
